name: Merge Conflict Labeler

on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: linux-amd64-cpu-8-hk
    steps:
      - name: check if prs are dirty
        uses: MrZ20/actions-label-merge-conflict@v1
        with:
          dirtyLabel: "merge-conflicts"
          invalidHeadLabel: "invalid-head-ref"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          continueOnMissingPermissions: "true"
          retryAfter: "10"
          retryMax: "2"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
          commentOnInvalidHead: "The source branch for this pull request is no longer available, so GitHub cannot evaluate whether it has merge conflicts. Please restore the branch, close this pull request, or open a new pull request from an available branch."
