name: buildkit-dockerfile-test-group1

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/buildkit-dockerfile-test-group1.yaml'
  pull_request:
    paths:
      - '.github/workflows/buildkit-dockerfile-test-group1.yaml'
  workflow_dispatch:

jobs:
  build-test:
    name: "build-test (${{ matrix.runner_info.arch }})"
    runs-on: ${{ matrix.runner_info.runner }}
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:9.0.0-a3-ubuntu22.04-py3.12

    strategy:
      fail-fast: false
      matrix:
        runner_info:
          - {runner: linux-aarch64-cpu-4-buildkit-gy006, arch: arm64}
          - {runner: linux-amd64-cpu-4-buildkit-gy006, arch: amd64}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Login to Quay (main account)
        uses: docker/login-action@v4
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push test image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile.test
          push: true
          tags: quay.io/ascend/vllm-benchmarks:test-${{ matrix.runner_info.arch }}-${{ github.sha }}
          provenance: false
