name: 'download models'

on:
  workflow_dispatch:
    inputs:
      model:
        required: true
        type: string
        description: 'Model name to be downloaded'
      image:
        required: true
        type: choice
        options:
          - m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10
        default: 'ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10'
        description: 'The docker image which will be loaded'
  schedule:
    - cron: '30 18 * * *'

defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    name: download models from modelscope
    runs-on: linux-arm64-npu-0
    container:
      image: ${{ github.event.inputs.image || 'ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10' }}
      env:
        HF_ENDPOINT: https://hf-mirror.com
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_TOKEN2: ${{ secrets.HF_TOKEN2 }}
        MS_TOKEN: ${{ secrets.MS_TOKEN }}
        HF_HUB_ETAG_TIMEOUT: 600
        HF_HUB_DOWNLOAD_TIMEOUT: 600
        HF_HUB_ENABLE_XET_UPLOAD: 0
        CURL_CA_BUNDLE: ""
        HF_HUB_DISABLE_XET: 1

    steps:
      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: Install dependencies
        run: |
          pip install modelscope

      - name: Download from modelscope (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Triggered manually: downloading model ${{ inputs.model }}"
          modelscope download --model ${{ inputs.model }}

      - name: Download from modelscope (scheduled trigger)
        if: github.event_name == 'schedule'
        run: |
          echo "Triggered on schedule: downloading model moonshotai/Kimi-K2-Instruct"
          modelscope download --model moonshotai/Kimi-K2-Instruct
