name: Accuracy Report
on:
  workflow_dispatch:
    inputs:
      vllm-ascend-branch:
        description: 'vllm-ascend branch:'
        required: true
        type: choice
        options:
          - main
          - v0.9.0rc2
          - v0.9.0-dev
          - v0.7.3-dev
      models:  
        description: 'models (choose "all" for all models):'
        required: true
        type: choice
        options:
          - all
          - Qwen/Qwen2.5-7B-Instruct
          - Qwen/Qwen2.5-VL-7B-Instruct
          - Qwen/Qwen3-8B-Base
        default: 'all'

jobs:
  download_reports:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ${{ fromJSON(
          (github.event.inputs.models == 'all' &&
            '["Qwen/Qwen2.5-7B-Instruct","Qwen/Qwen2.5-VL-7B-Instruct","Qwen/Qwen3-8B-Base"]') ||
          (github.event.inputs.models == 'Qwen/Qwen2.5-7B-Instruct' &&
            '["Qwen/Qwen2.5-7B-Instruct"]') ||
          (github.event.inputs.models == 'Qwen/Qwen2.5-VL-7B-Instruct' &&
            '["Qwen/Qwen2.5-VL-7B-Instruct"]') ||
          (github.event.inputs.models == 'Qwen/Qwen3-8B-Base' &&
            '["Qwen/Qwen3-8B-Base"]')
         ) }}
        
        version: [0, 1]
        exclude:
          - model: 'Qwen/Qwen2.5-VL-7B-Instruct'
            version: 1
      fail-fast: false     

    name: Download ${{ matrix.model }} V${{ matrix.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get base model name
        id: get_basename
        run: |
          model_base_name=$(basename "${{ matrix.model }}")
          echo "model_base_name=$model_base_name" >> $GITHUB_OUTPUT
        shell: bash

      - name: Query artifact run id
        id: get_run_id
        run: |
          # 1. 定义上游仓库名称
          UPSTREAM_REPO="nv-action/vllm-benchmarks"  # 替换为实际的上游仓库名称
          
          ARTIFACT_PATTERN="${{ github.event.inputs.vllm-ascend-branch }}-${{ steps.get_basename.outputs.model_base_name }}-V${{ matrix.version }}-report"
          echo "Querying artifacts with pattern: $ARTIFACT_PATTERN"
          
          # 2. 修改为查询上游仓库的artifacts
          ARTIFACT_JSON=$(gh api --paginate /repos/$UPSTREAM_REPO/actions/artifacts || echo "{}")
          
          RUN_ID=$(echo "$ARTIFACT_JSON" | \
            jq -s -r --arg pattern "$ARTIFACT_PATTERN" \
            '[.[].artifacts[]] | map(select(.name | test($pattern))) | sort_by(.created_at) | last | .workflow_run.id // empty')
          
          if [ -z "$RUN_ID" ]; then
            echo "::warning::No artifact found matching pattern $ARTIFACT_PATTERN. Skipping download."
            echo "runid=" >> $GITHUB_OUTPUT
          else
            echo "Found matching artifact with run ID: $RUN_ID"
            echo "runid=$RUN_ID" >> $GITHUB_OUTPUT
          fi
        env:
          # 3. 使用有上游仓库访问权限的PAT
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Download Artifact
        if: ${{ steps.get_run_id.outputs.runid != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.vllm-ascend-branch }}-${{ steps.get_basename.outputs.model_base_name }}-V${{ matrix.version }}-report
          path: ./accuracy/accuracy_report_bak
          # 4. 使用有上游仓库访问权限的PAT
          github-token: ${{ secrets.PAT_TOKEN }}
          # 5. 指定上游仓库
          repository: nv-action/vllm-benchmarks  # 替换为实际的上游仓库名称
          run-id: ${{ steps.get_run_id.outputs.runid }}
          
      - name: Upload reports artifact
        if: ${{ steps.get_run_id.outputs.runid != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ steps.get_basename.outputs.model_base_name }}-v${{ matrix.version }}
          path: ./accuracy/accuracy_report_bak/*.md
          retention-days: 1
