name: accuarcy report
on:
  workflow_run:
    workflows: ["accuarcy test"]
    types: [completed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'choose a dev branch to pr'
        required: true
      vllm-ascend-version:
        description: 'what vllm-ascend version to accuracy test?'
        required: true
        type: string
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      # - name: Checkout vllm-project/vllm-ascend repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: vllm-project/vllm-ascend
      #     path: ./vllm-ascend
      #     ref: v0.7.3rc2  
      #     fetch-depth: 0

      - name: Debug List Artifacts
        run: gh api /repos/${{ github.repository }}/actions/artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Query artifact run id for Qwen2.5-VL-7B-Instruct V0 latest artifact
      #   id: get_Qwen2_5_VL_7B_Instruct_latest_run_id_V0
      #   run: |
      #     ARTIFACT_JSON=$(gh api "repos/${{ github.repository }}/actions/artifacts")
      #     RUN_ID=$(echo "$ARTIFACT_JSON" | \
      #       jq -r '[.artifacts[] | select(.name=="${{ github.event.inputs.vllm-ascend-version }}-Qwen2.5-VL-7B-Instruct-V0-report")] | sort_by(.created_at) | last | .workflow_run.id')
      #     echo "runid=$RUN_ID" >> "$GITHUB_OUTPUT"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Query artifact run id for Qwen2.5-7B-Instruct V0 latest artifact
        id: get_Qwen2_5_7B_Instruct_latest_run_id_V0
        run: |
          ARTIFACT_JSON=$(gh api repos/${{ github.repository }}/actions/artifacts)
          RUN_ID=$(echo "$ARTIFACT_JSON" | \
            jq -r '[.artifacts[] | select(.name=="${{ github.event.inputs.vllm-ascend-version }}-Qwen2.5-7B-Instruct-V0-report")] | sort_by(.created_at) | last | .workflow_run.id')
          echo "runid=$RUN_ID" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Query artifact run id for Llama-3.1-8B-Instruct V0 latest artifact
      #   id: get_Llama_3_1_8B_Instruct_latest_run_id_V0
      #   run: |
      #     ARTIFACT_JSON=$(gh api repos/${{ github.repository }}/actions/artifacts)
      #     RUN_ID=$(echo "$ARTIFACT_JSON" | \
      #       jq -r '[.artifacts[] | select(.name=="${{ github.event.inputs.vllm-ascend-version }}-Llama-3.1-8B-Instruct-V0-report")] | sort_by(.created_at) | last | .workflow_run.id')
      #     echo "runid=$RUN_ID" >> $GITHUB_OUTPUT
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Download Qwen/Qwen2.5-VL-7B-Instruct V0 Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ${{ github.event.inputs.vllm-ascend-version }}-Qwen2.5-VL-7B-Instruct-V0-report
      #     path: ./accuracy/result/V0
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     repository: nv-action/vllm-benchmarks 
      #     run-id: ${{ steps.get_Qwen2_5_VL_7B_Instruct_latest_run_id_V0.outputs.runid }}

      - name: Download Qwen/Qwen2.5-7B-Instruct V0 Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.vllm-ascend-version }}-Qwen2.5-7B-Instruct-V0-report
          path: ./accuracy/result/V0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: nv-action/vllm-benchmarks 
          run-id: ${{ steps.get_Qwen2_5_7B_Instruct_latest_run_id_V0.outputs.runid }}

      # - name: Download meta-llama/Llama-3.1-8B-Instruct Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ${{ github.event.inputs.vllm-ascend-version }}-Llama-3.1-8B-Instruct-V0-report
      #     path: ./accuracy/result/V0
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     repository: nv-action/vllm-benchmarks 
      #     run-id: ${{ steps.get_Llama_3_1_8B_Instruct_latest_run_id_V0.outputs.runid }}

      - name: Display File
        working-directory: ./accuracy/result/V0
        run: |
          # cat ./Qwen2.5-VL-7B-Instruct.md
          # cat ./Llama-3.1-8B-Instruct.md
          cat ./Qwen2.5-7B-Instruct.md
      
      - name: Create Pull Request for markdown update
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: ${{ github.ref_name }}
          branch: auto-pr/accuracy-test
          commit-message: "Update generated markdown report"
          add-paths: |
            accuracy/result/V0/*.md
          title: "[DOC]Update accuracy report"
          body: |
            The accuracy results running on Ascend NPU have changed, I'm updating the report.
            Please review the changes.

            - [Workflow run][1]
            - [Qwen2.5-7B-Instruct accuracy report][2]
            # - [Llama-3.1-8B-Instruct accuracy report][3]
            # - [Qwen2.5-VL-7B-Instruct accuracy report][4]

            [1]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            [2]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.get_Qwen2_5_7B_Instruct_latest_run_id_V0.outputs.runid }}
            # [3]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.get_Llama_3_1_8B_Instruct_latest_run_id_V0.outputs.runid }}
            # [4]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ steps.get_Qwen2_5_VL_7B_Instruct_latest_run_id_V0.outputs.runid }}