name: Accuracy Report
on:
  workflow_dispatch:
    inputs:
      vllm-ascend-branch:
        description: 'vllm-ascend branch:'
        required: true
        type: choice
        options:
          - main
          - v0.7.3-dev
      models:  
        description: 'models (choose "all" for all models):'
        required: true
        type: choice
        options:
          - all
          - Qwen/Qwen2.5-7B-Instruct
          - Qwen/Qwen2.5-VL-7B-Instruct
          - Qwen/Qwen3-8B-Base
        default: 'all'

jobs:
  download_reports:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ${{ fromJSON((github.event.inputs.models == 'all' && '["Qwen/Qwen2.5-7B-Instruct","Qwen/Qwen2.5-VL-7B-Instruct","Qwen/Qwen3-8B-Base"]') || format('["{0}"]', github.event.inputs.models)) }}
        version: [0, 1]
        exclude:
          - model: 'Qwen/Qwen2.5-VL-7B-Instruct'
            version: 1
      fail-fast: false     

    name: Download ${{ matrix.model }} V${{ matrix.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.vllm-ascend-branch }}

      - name: Get base model name
        id: get_basename
        run: |
          model_base_name=$(basename "${{ matrix.model }}")
          echo "model_base_name=$model_base_name" >> $GITHUB_OUTPUT
        shell: bash

      - name: Query artifact run id
        id: get_run_id
        run: |
          ARTIFACT_NAME="${{ github.event.inputs.vllm-ascend-branch }}-${{ steps.get_basename.outputs.model_base_name }}-V${{ matrix.version }}-report"
          echo "Querying artifact: $ARTIFACT_NAME"
          
          ARTIFACT_JSON=$(gh api /repos/${{ github.repository }}/actions/artifacts || echo "{}")
          RUN_ID=$(echo "$ARTIFACT_JSON" | \
            jq -r --arg name "$ARTIFACT_NAME" \
            '[.artifacts[] | select(.name == $name)] | sort_by(.created_at) | last | .workflow_run.id // empty')
          
          if [ -z "$RUN_ID" ]; then
            echo "::warning::Artifact $ARTIFACT_NAME not found. Skipping download."
            echo "runid=" >> $GITHUB_OUTPUT
          else
            echo "Found artifact with run ID: $RUN_ID"
            echo "runid=$RUN_ID" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Download Artifact
        if: ${{ steps.get_run_id.outputs.runid != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.vllm-ascend-branch }}-${{ steps.get_basename.outputs.model_base_name }}-V${{ matrix.version }}-report
          path: ./accuracy/accuracy_report
          github-token: ${{ secrets.GITHUB_TOKEN  }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get_run_id.outputs.runid }}
          
      - name: Upload reports artifact
        if: ${{ steps.get_run_id.outputs.runid != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ steps.get_basename.outputs.model_base_name }}-v${{ matrix.version }}
          path: ./accuracy/accuracy_report/*.md
          retention-days: 1

  create_pr:
    runs-on: ubuntu-latest
    needs: download_reports
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.vllm-ascend-branch }}

      - name: Setup workspace
        run: mkdir -p ./accuracy/accuracy_report

      - name: Download all reports
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pattern: 'report-*'
          path: ./accuracy/accuracy_report
          merge: true
          if_no_artifact_found: warn
          
      - name: Flatten report directory structure
        run: |
          find ./accuracy/accuracy_report -type f -name '*.md' -exec mv {} ./accuracy/accuracy_report/ \;
          find ./accuracy/accuracy_report -mindepth 1 -type d -empty -delete
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: ${{ github.event.inputs.vllm-ascend-branch }}
          branch: auto-pr/accuracy-test-${{ github.run_id }}
          commit-message: "Update accuracy reports for ${{ github.event.inputs.vllm-ascend-branch }}"
          add-paths: |
            ./accuracy/accuracy_report/*.md
          title: "[Doc] Update accuracy reports for ${{ github.event.inputs.vllm-ascend-branch }}"
          body: |
            The accuracy results running on Ascend NPU have changed, updating reports for:
            ${{ 
              github.event.inputs.models == 'all' 
                && 'All models (Qwen2.5-7B-Instruct, Qwen2.5-VL-7B-Instruct, Qwen3-8B-Base)' 
                || github.event.inputs.models 
            }}
            
            - [Workflow run][1]
            
            [1]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
