name: accuarcy report
on:
  workflow_run:
    workflows: ["accuarcy test"]
    types: [completed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'choose a new dev branch'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    steps:

      - name: Validate branch name
        id: validate_branch
        run: |
          if [[ "${{ github.event.inputs.branch }}" =~ -dev$ ]]; then
            echo "Branch name is valid."
          else
            echo "Error: The selected branch does not end with '-dev'."
            exit 1
          fi
          SANITIZED_BRANCH_NAME="${{ github.event.inputs.branch }}"
          echo "SANITIZED_BRANCH_NAME=${SANITIZED_BRANCH_NAME}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Checkout vllm-project/vllm-ascend repo
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm-ascend
          path: ./vllm-ascend
          ref: v0.7.3rc2  
          fetch-depth: 0
      - name: Debug List Artifacts
        run: gh api /repos/${{ github.repository }}/actions/artifacts
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Download Qwen/Qwen2.5-VL-7B-Instruct Artifact
        uses: actions/download-artifact@v4
        with:
          name: Qwen2.5-VL-7B-Instruct-accuracy-reports
          path: ./accuracy/result
          github-token: ${{ secrets.PAT_TOKEN }}
          repository: nv-action/vllm-benchmarks 
          run-id: 14421469928

      - name: Download Qwen/Qwen2.5-7B-Instruct Artifact
        uses: actions/download-artifact@v4
        with:
          name: Qwen2.5-7B-Instruct-accuracy-reports
          path: ./accuracy/result
          github-token: ${{ secrets.PAT_TOKEN }}
          repository: nv-action/vllm-benchmarks 
          run-id: 14421469928

      - name: Download meta-llama/Llama-3.1-8B-Instruct Artifact
        uses: actions/download-artifact@v4
        with:
          name: Llama-3.1-8B-Instruct-accuracy-reports
          path: ./accuracy/result
          github-token: ${{ secrets.PAT_TOKEN }}
          repository: nv-action/vllm-benchmarks 
          run-id: 14421469928

      - name: Display File
        working-directory: ./accuracy/result
        run: |
          cat ./Qwen2.5-VL-7B-Instruct.md
          cat ./Llama-3.1-8B-Instruct.md
          cat ./Qwen2.5-VL-7B-Instruct.md
      
      - name: Create Pull Request for markdown update
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: ${{ env.SANITIZED_BRANCH_NAME }}
          branch: auto-pr/accuracy-test
          commit-message: "Update generated markdown report"
          add-paths: |
            accuracy/result/*.md
          title: "Update markdown report"
          body: |
            The accuracy results running on Ascend NPU have changed, I'm updating the report.
            Please review the changes.

            - [Workflow run][1]

            [1]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}