name: Accuracy Report
on:
  workflow_dispatch:
    inputs:
      vllm-ascend-branch:
        description: 'vllm-ascend branch:'
        required: true
        type: choice
        options:
          - main
          - v0.7.3-dev
      models:  
        description: 'models:'
        required: true
        type: choice
        options:
          - Qwen/Qwen2.5-7B-Instruct
          - Qwen/Qwen2.5-VL-7B-Instruct
          - Qwen/Qwen3-8B-Base
        default: 'Qwen/Qwen2.5-7B-Instruct'
        multiple: true

jobs:
  download_reports:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ${{ github.event.inputs.models }}
        version: [0, 1]
      exclude:
        # 排除VL模型的V1版本（根据之前的排除规则）
        - model: 'Qwen/Qwen2.5-VL-7B-Instruct'
          version: 1
      fail-fast: false

    name: Download ${{ matrix.model }} V${{ matrix.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Get base model name
        id: get_basename
        run: |
          model_base_name=$(basename "${{ matrix.model }}")
          echo "model_base_name=$model_base_name" >> $GITHUB_OUTPUT
        shell: bash

      - name: Query artifact run id
        id: get_run_id
        run: |
          ARTIFACT_NAME="${{ github.event.inputs.vllm-ascend-branch }}-${{ steps.get_basename.outputs.model_base_name }}-V${{ matrix.version }}-report"
          ARTIFACT_JSON=$(gh api /repos/${{ github.repository }}/actions/artifacts)
          RUN_ID=$(echo "$ARTIFACT_JSON" | \
            jq -r --arg name "$ARTIFACT_NAME" \
            '[.artifacts[] | select(.name == $name)] | sort_by(.created_at) | last | .workflow_run.id')
          
          if [ -z "$RUN_ID" ] || [ "$RUN_ID" = "null" ]; then
            echo "::warning::Artifact $ARTIFACT_NAME not found"
            echo "runid=" >> $GITHUB_OUTPUT
          else
            echo "runid=$RUN_ID" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Artifact
        if: ${{ steps.get_run_id.outputs.runid != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.vllm-ascend-branch }}-${{ steps.get_basename.outputs.model_base_name }}-V${{ matrix.version }}-report
          path: ./docs/source/developer_guide/evaluation/accuracy_report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: vllm-project/vllm-ascend
          run-id: ${{ steps.get_run_id.outputs.runid }}

  create_pr:
    runs-on: ubuntu-latest
    needs: download_reports
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          path: repo

      - name: Copy downloaded reports
        run: |
          mkdir -p repo/docs/source/developer_guide/evaluation/accuracy_report
          cp -r ./docs/source/developer_guide/evaluation/accuracy_report/* repo/docs/source/developer_guide/evaluation/accuracy_report/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PR_TOKEN }}
          base: ${{ github.event.inputs.branch }}
          branch: auto-pr/accuracy-test-${{ github.run_id }}
          commit-message: "Update accuracy reports for ${{ github.event.inputs.branch }}"
          add-paths: |
            docs/source/developer_guide/evaluation/accuracy_report/*.md
          title: "[Doc] Update accuracy reports for ${{ github.event.inputs.branch }}"
          body: |
            The accuracy results running on Ascend NPU have changed, updating reports for:
            ${{ join(github.event.inputs.models, ', ') }}
            
            - [Workflow run][1]
            
            [1]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}