name: 'benchmarks'

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit id of repo vllm-project/vllm-ascend to fetch'
        required: true
      commit_title:
        description: 'Commit title'
        required: true
        default: 'None commit message found on this commit'


# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    name: run benchmarks (self-host)
    runs-on: ascend-arcch64  # actionlint-ignore: runner-label

    container:
      image: quay.io/ascend/cann:8.0.0-910b-ubuntu22.04-py3.10
      volumes:
        - /usr/local/dcmi:/usr/local/dcmi
        - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
        - /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/
        - /home/wl/actions-runner/_work/cache:/github/home/.cache/
      options: >-
        --device /dev/davinci6
        --device /dev/davinci_manager
        --device /dev/devmm_svm
        --device /dev/hisi_hdc
      env:
        HF_ENDPOINT: https://hf-mirror.com
        SHAREGPT_PATH: /github/home/.cache/datasets/ShareGPT_V3_unfiltered_cleaned_split.json
        LLAMA_3_1_8B_PATH: /github/home/.cache/models/Meta-Llama-3-8B-Instruct
    steps:
      - name: Check npu and CANN info
        run: |
          npu-smi info
          cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info

      - name: Check env var
        run: |
          echo ${SHAREGPT_PATH}
          echo ${LLAMA_3_1_8B_PATH}
          echo ${RESULTS_FOLDER}
          echo "commit_id is ${{ github.event.inputs.commit_id }}"
          echo "commit_title is ${{ github.event.inputs.commit_title }}"

      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: Install system dependencies
        run: |
          apt-get update -y
          apt-get -y install git jq wget curl lsof

      - name: Setup proxy
        run: |
          nohup /github/home/.cache/clash/clash \
          -d ./clash -d /github/home/.cache/clash > /github/home/.cache/clash/clash.log 2>&1 &

          # wait for clash up
          sleep 5
          
          git config --global http.proxy "http://127.0.0.1:7890"
          git config --global https.proxy "http://127.0.0.1:7890" 

      - name: Checkout vllm-project/vllm repo
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm
          path: ./

      - name: Checkout vllm-project/vllm-ascend repo
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm-ascend
          path: ./vllm-ascend
          fetch-depth: 0

      - name: Install vllm-project/vllm from source
        run: |
          VLLM_TARGET_DEVICE=empty pip install -e .

      - name: Install vllm-project/vllm-ascend
        working-directory: ./vllm-ascend
        run: |
          pip install -e .

      - name: Install torch-npu
        run: |
          mkdir pta
          cd pta
          wget https://pytorch-package.obs.cn-north-4.myhuaweicloud.com/pta/Daily/v2.5.1/20250218.4/pytorch_v2.5.1_py310.tar.gz
          tar -xvf pytorch_v2.5.1_py310.tar.gz
          pip install ./torch_npu-2.5.1.dev20250218-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
          cd ..
          rm -rf pta

      - name: Checkout cosdt/vllm-benchmarks repo
        uses: actions/checkout@v4
        with:
          repository: cosdt/vllm-benchmarks
          path: ./vllm-benchmarks
      
      - name: Install benchmark dependencies
        working-directory: ./vllm-benchmarks
        run: |
          pip install -r requirements.txt

      - name: Run benchmarks
        working-directory: ./vllm-benchmarks
        run: | 
          bash .elastic/nightly-benchmarks/scripts/run-performance-benchmarks.sh
      
      - name: Test ls RESULTS_FOLDER
        working-directory: ./vllm-benchmarks
        run: |
          ls benchmarks/results
          