name: Test NPU 4
on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: linux-arm64-npu-4
    container:
      image: ascendai/cann:latest
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 3600