name: '_ascend_npu_benchmark'

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - linux-arm64-npu-4
        default: 'linux-arm64-npu-1'
        description: 'The runner selected to run on'
      image:
        required: true
        type: choice
        options:
          - quay.io/ascend/cann:8.0.0-910b-ubuntu22.04-py3.10
          - ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10
        default: 'ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10'
        description: 'The docker image which will be loaded'


# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    name: run benchmarks for torch_npu
    runs-on: ${{ github.event.inputs.runner || 'linux-arm64-npu-1' }}"
    container:
      image: ${{ github.event.inputs.image || 'ascendai/cann:latest' }}"
      env:
        HF_ENDPOINT: https://hf-mirror.com
        VLLM_USE_MODELSCOPE: true
    steps:
      - name: test es
        working-directory: ./vllm-ascend
        run: |
          commit_id_cur=$(curl -k -X POST "${{ secrets.ES_OM_DOMAIN }}/vllm_benchmark_throughput/_search" \
          -H "Content-Type: application/x-ndjson" \
          -H "Authorization: ${{ secrets.ES_OM_AUTHORIZATION }}" \
          -d '{
            "_source": false,
            "size": 10000,
            "query": {
              "match_all": {}
            },
            "sort": [
              {
                "created_at": {
                  "order": "desc"
                }
              }
            ]
          }' | jq -r '.hits.hits[]._id' | cut -d'_' -f1)
          echo "cur_commit_id: $commit_id_cur""