name: 'single_npu_test'

on:
  workflow_dispatch:
    inputs:
      runner:
        required: true
        type: choice
        options:
          - linux-arm64-npu-1
        default: 'linux-arm64-npu-1'
        description: 'The runner selected to run on'
      image:
        required: true
        type: choice
        options:
          - ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10
        default: 'ascendai/cann:8.0.0-910b-ubuntu22.04-py3.10'
        description: 'The docker image which will be loaded'
  # workflow_call:
  #   inputs:
  #     runner:
  #       required: true
  #       type: string
  #       description: 'The runner selected to run on'
  #     image:
  #       required: true
  #       type: string
  #       description: 'The docker image which will be loaded'

# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

jobs:
  benchmark:
    name: run benchmarks for torch_npu
    runs-on: ${{ github.event.inputs.runner || 'linux-arm64-npu-1' }}
    container:
      image: ${{ github.event.inputs.image }}
      env:
        HF_ENDPOINT: https://hf-mirror.com
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        DATASET_SOURCE: ModelScope
        ES_OM_DOMAIN: ${{ secrets.ES_OM_DOMAIN }}
        ES_OM_AUTHORIZATION: ${{ secrets.ES_OM_AUTHORIZATION }}
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - name: Check env
        run: |
          echo "hf_endpoint: $HF_ENDPOINT"
          echo "hf_token: $HF_TOKEN"
          echo "hf: ${{ secrets.HF_TOKEN }}"
                  
