#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
#

name: 'cllouud e2e test'

on:
  workflow_dispatch:


defaults:
  run:
    shell: bash -el {0}


jobs:
  test:
    strategy:
      matrix:
        # os: [linux-arm64-npu-0, linux-arm64-npu-1, linux-arm64-npu-2, linux-arm64-npu-4, linux-arm64-npu-8]
        # os: [linux-aarch64-a2-0, linux-aarch64-a2-1, linux-aarch64-a2-2, linux-aarch64-a2-4, linux-aarch64-a2-8]
        # os: [linux-aarch64-910c-1, linux-aarch64-910c-2, linux-aarch64-910c-4]
        # os: [linux-aarch64-a2-1]
        # os: [linux-aarch64-910c-1, linux-aarch64-910c-2, linux-aarch64-910c-4]
        os: [linux-aarch64-a3-2, linux-aarch64-a3-4, linux-aarch64-a3-8, linux-aarch64-a3-16]
        ## 测试 aicc 集群
        # os: [aicc-linux-arm64-npu-1, aicc-linux-arm64-npu-4]
    name: vLLM Ascend test
    runs-on: ${{ matrix.os }}
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.1.rc1-910b-ubuntu22.04-py3.10
    steps:
      - name: Check npu and CANN info
        run: |
          npu-smi info
          cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info

      - name: Config mirrors
        run: |
          sleep 3600
      #     sed -Ei 's@(ports|archive).ubuntu.com@cache-service.nginx-pypi-cache.svc.cluster.local:8081@g' /etc/apt/sources.list
      #     pip config set global.index-url http://cache-service.nginx-pypi-cache.svc.cluster.local/pypi/simple
      #     pip config set global.trusted-host cache-service.nginx-pypi-cache.svc.cluster.local
      #     apt-get update -y
      #     apt install git -y

      # - name: Checkout vllm-project/vllm-ascend repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: Potabk/vllm-ascend
      #     ref: ci_opt
      #     path: ./
    
