name: 'ascend test / nightly'

on:
  #schedule:
      # Run test at 24:00 Beijing time (UTC+8)
      #- cron: "0 16 * * *"
  workflow_dispatch:
  pull_request: 
    branches:
      - 'main'
      - '*-dev'
    paths:
      - 'tests/e2e/nightly/**'
      - '.github/workflows/vllm_ascend_test_nightly.yaml'

# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

# only cancel in-progress runs of the same workflow
# and ignore the lint / 1 card / 4 cards test type
concurrency:
  group: ascend-nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qwen3-32b-int8:
    strategy:
      matrix:
        os: [linux-aarch64-a2-4]
    uses: ./.github/workflows/_e2e_nightly.yaml
    with:
      vllm: v0.11.0
      runner: ${{ matrix.os }}
      tests: tests/e2e/nightly/models/test_qwen3_32b_int8.py
